# Project Information
group=com.zientis
version=0.1.0-ALPHA

# Java Configuration
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Kotlin DSL
kotlin.code.style=official

# Dependencies Versions
paperVersion=1.20.6-R0.1-SNAPSHOT
bentoboxVersion=1.20.6
slimefunVersion=RC-32
vaultVersion=1.7
mariadbVersion=3.3.2
redisVersion=5.0.2
hikariVersion=5.1.0
junitVersion=5.10.1
mockitoVersion=5.8.0